# Use postgres/example user/password credentials
version: '3.1'

services:
  app_server:
    build: .
    image: gcr.io/treeo-dev/treeo-api-develop:latest
    pull_policy: always
    network_mode: host
    env_file:
      - .env
    restart: always
  
  app_nginx:
    image: nginx:1.20.2-alpine
    container_name: nginx
    restart: always
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - app_server
