# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: mdillon/postgis:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:5432
    volumes: 
      # - ./postgresdata:/var/lib/postgresql/data
      - ./database/database.sql:/docker-entrypoint-initdb.d/1-dbinit.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: "redis:alpine"
    # command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
     - 6379:6379
    volumes:
     - $PWD/redis-data:/var/lib/redis
      # - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
     - REDIS_REPLICATION_MODE=master

  producer:
    build:
      context: ./pubsub/producer
      dockerfile: Dockerfile
    ports:
      - 9182:9012
    restart: always
    env_file:
      - ./pubsub/producer/.env
    depends_on:
      - "consumer"
      - "db"
  
  consumer:
    build:
      context: ./pubsub/consumer
      dockerfile: Dockerfile
    network_mode: host
    env_file:
      - ./pubsub/consumer/.env
    restart: always
 