
version: '3.1'

services:
  producer:
    build:
      context: ./pubsub/producer
      dockerfile: Dockerfile
    ports:
      - 9182:9012
    restart: always
    env_file:
      - ./pubsub/producer/.env
    depends_on:
      - "consumer"

  consumer:
    build:
      context: ./pubsub/consumer
      dockerfile: Dockerfile
    network_mode: host
    env_file:
      - ./pubsub/consumer/.env
    restart: always
